nile/config/routes.rb
Nile::Application.routes.draw do
  get "home/index"


   root :to => 'home#index'
   match '/company/:id' => 'home#company', :as => 'company'
   match '/cause/:id' => 'home#cause', :as => 'cause'
   match '/organization/:id' => 'home#organization', :as => 'organization'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

nile/app/models/cause.rb
class Cause < ActiveRecord::Base
  attr_accessible :name
end

nile/app/models/causeorg.rb
class Causeorg < ActiveRecord::Base
  attr_accessible :cause_id, :org_id
end

nile/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :charity, :income, :name, :url
end

nile/app/models/comporg.rb
class Comporg < ActiveRecord::Base
  attr_accessible :comp_id, :org_id
end

nile/app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name
end

nile/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

nile/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @companies = Company.all
    @companies.each do |companies|
      puts company_path(companies.id)
    end
    @causes = Cause.all
    @organizations = Organization.all
  end
   
   def company
    @company = Company.where(:id=>params[:id]).first
    rel = Comporg.where(:comp_id=> @company.id).collect(&:org_id)
    @orgs = Organization.where(:id => rel)
    inter = @orgs.collect(&:id)
    rel2 = Causeorg.where(:org_id=>inter).collect(&:cause_id)
    @causes = Cause.where(:id=>rel2)
   end

   # def cause
   #  @cause = Cause.find(params[:id])
   #  rel = Causeorg.where(:cause_id=> @cause.id).collect(&:org_id)
   #  @orgs = Organization.where(:id => rel)
   #  rel2= Comporg.where(:comp_id=> @orgs.id).collect(&:comp_id)
   #  @companies = Company.where(:id=>rel2)
   # end 

   # def organization
   #  @org = Organization.find(params[:id])
   #  rel = Causeorg.where(:org_id=> @org.id).collect(&:cause_id)
   #  @causes = Cause.where(:id => rel)
   #  rel2= Comporg.where(:org_id=> @org.id).collect(&:comp_id)
   #  @companies = Company.where(:id=>rel2)
   # end 

end

nile/app/helpers/application_helper.rb
module ApplicationHelper
end

nile/app/helpers/home_helper.rb
module HomeHelper
end

nile/app/views/home/company.html.erb
<div class="content_pos" style="font-size:20px;width:800px;height:800px">
   <h1><%= @company.name %></h1>
   <img src='<%= @company.url %>'> 
   <p>
    Net profit = <%= @company.profit %>
    Net ratio = <%= @company.ratio %>
   </p>
   <h2> Causes they support </h2>
   <ul>
   <% @causes.each do |cause| %>
    <li><%= cause.name%></li>
   <% end %>
 </ul>
 <h2> Organizations they donate to  </h2>
   <ul>
   <% @orgs.each do |org| %>
    <li><%= org.name%></li>
   <% end %>
 </ul>
</div>

nile/app/views/home/index.html.erb
<div class="content_pos" style="font-size:20px;width:800px;height:800px">
<div class="row">
  <div class="span3">
    <h1>Comapnies</h1>
    <ul>
    <% @companies.each do |company|%>
    <li><a href="<%= company_path(company)%>"> <%= company.name %></a></li>
    <% end %>
  </ul>
  </div>
  <div class="span3">
    <h1>Causes</h1>
    <ul>
    <% @causes.each do |cause|%>
    <li><a href="<%= cause_path(cause.id)%>"><%= cause.name %></a></li>
    <% end %>
  </ul>
  </div>
  <div class="span3">
    <h1>Organizations</h1>
    <ul>
    <% @organizations.each do |organization|%>
     <li><a href="<%= organization_path(organization.id)%>"> <%=organization.name %></a></li>
    <% end %>
  </ul>
  </div>
</div>
</div>

nile/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#ContributingCode Sprint</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
       <a class="brand" href="/">Nile</a>         
      </div>
    </div>
  </div>

   <%= yield %>


</body>
</html>